### ISSUE TITLE
Overlapping class hours

### ISSUE THREAD

**Issue by iseolin76** [baekteun/TodayWhat#2]
# What happened?

<img width="333" alt="스크린샷 2022-06-15 오후 12 14 21" src="https://user-images.githubusercontent.com/65021545/173730620-1c893cb0-ab48-4df9-9ae6-cedd16f5975a.png">

The fourth period appears twice.

## How to reproduce

**Choose like this**
It is based on June 15th.
광주소프트웨어마이스터고등학교 - 3학년 2반 - 시간표

**Comment by baekteun** [comment]
내용물이 완전히 같은 경우를 필터링하는 방식로 1.2버전에 반영되었습니다!

**Comment by baekteun** [comment]
내용물이 완전히 같은 경우를 필터링하는 방식으로 1.2버전에 반영되었습니다!
