### ISSUE TITLE
Unable to check

### ISSUE THREAD

**Issue by iseolin76** [baekteun/TodayWhat#6]
# What happened?

<img width="324" alt="스크린샷 2022-06-17 오후 12 14 25" src="https://user-images.githubusercontent.com/65021545/174217839-75d17ec9-bc72-471c-8665-bf5f1655727f.png">
<img width="308" alt="스크린샷 2022-06-17 오후 12 20 03" src="https://user-images.githubusercontent.com/65021545/174218292-434548b5-3d19-4638-951b-d0d3e0461784.png">
<img width="311" alt="스크린샷 2022-06-17 오후 12 20 22" src="https://user-images.githubusercontent.com/65021545/174218326-5f801e9f-f25b-4239-a096-8e54cd6b9d76.png">

Timetable and school meals are not checked.
Message - ~~ 를 찾을 수 없어요!

I think it's ["Neis API"](https://open.neis.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=OPEN17320190722180924242823&infSeq=1)
Other products that use that API work well
Something seems to have gone wrong inside the app!

## What I did

Timetable and Meal Check

**Comment by baekteun** [comment]
@iseolin76 What happens when you press the '새로고침' button?
